<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Callum Barnsley">

<title>Effects of Eye-Protection Devices on Eye Strain During Prolonged Gaming</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="mini project_files/libs/clipboard/clipboard.min.js"></script>
<script src="mini project_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="mini project_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="mini project_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="mini project_files/libs/quarto-html/popper.min.js"></script>
<script src="mini project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mini project_files/libs/quarto-html/anchor.min.js"></script>
<link href="mini project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mini project_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mini project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mini project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mini project_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Effects of Eye-Protection Devices on Eye Strain During Prolonged Gaming</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Callum Barnsley </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="background" class="level1">
<h1><strong>Background</strong></h1>
<p>With the recent growth in computer use, the potential risks associated with prolonged screen exposure have also increased. These risks include eye strain, discomfort, and visual fatigue caused by screen light, particularly blue light (Sheppard &amp; Wolffsohn, 2018). Eye strain, referred to as computer vision syndrome has been documented to occur among people who engage in activities with extended screen time use (Rosenfield, 2016).&nbsp;</p>
<p>In response to these concerns, gaming eyewear is a product currently marketed to mitigate these effects, typically using blue-light filters to reduce visual strain. Standard gaming glasses generally provide a fixed tint on the lenses. While these do reduce the exposure to blue light , they do not dynamically adjust the variations in screen brightness nor the chromatic intensity. In contrast, adaptive blue-light filtering devices dynamically adjust the filtering based on on-screen chroma and brightness. This has the potential to provide more protection during extended gaming sessions.&nbsp;</p>
<p>Despite the growing commercial adoption, understanding how adaptive devices compare to both standard gaming glasses and no protection, and whether any benefits persist over multiple gaming sessions, it is essential to do a statistical analysis to evaluate their effectiveness.</p>
<p>This study aims to test three hypothesis:</p>
<p><strong>1. Device Effect Within Session</strong></p>
<p>To examine whether the type of device influences eye strain score within a session:</p>
<p><strong>H₀₁ (Null Hypothesis):</strong></p>
<p>There is no effect of the device on the mean eye strain score. The mean eye strain does not change between the adaptive blue filter, standard gaming glasses and no protection within a session.</p>
<p>H0:μadaptive = μstandard = μnone</p>
<p><strong>H₁₁ (Alternative Hypothesis):</strong></p>
<p>There is an effect of the device on the mean eye strain score, the adaptive blue filter results in a lower mean eye strain score than both standard gaming glasses and no protection within a session.</p>
<p>H11:μadaptive &lt; μstandard and μadaptive &lt; μnone</p>
<section id="persistence-session-effect-for-adaptive-device" class="level3">
<h3 class="anchored" data-anchor-id="persistence-session-effect-for-adaptive-device"><strong>2. Persistence (Session Effect for Adaptive Device)</strong></h3>
<p>To examine whether the adaptive device maintains or improves its benefit across sessions:</p>
<p><strong>H₀₂ (Null Hypothesis):<br>
</strong>Participants us the adaptive blue filter, the mean eye score in session 2 is greater than or equal to the mean eye strain score in session 1,</p>
<p>H0:μadaptive,session2 ≥ μadaptive,session1</p>
<p><strong>H₁₂ (Alternative Hypothesis):<br>
</strong>Participants using the adaptive blue filter, the mean eye strain score in session 2 is less than the mean eye strain in session 1.</p>
<p>H1:μadaptive,session2 &lt; μadaptive,session1</p>
</section>
<section id="baseline-benefit-of-standard-gaming-glasses" class="level3">
<h3 class="anchored" data-anchor-id="baseline-benefit-of-standard-gaming-glasses"><strong>3. Baseline Benefit of Standard Gaming Glasses</strong></h3>
<p>To examine whether standard gaming glasses reduce eye strain compared to no protection:</p>
<p><strong>H₀₃ (Null Hypothesis):</strong></p>
<p>There is no difference in the mean for the eye strain score between standard gaming glasses and no protection.</p>
<p>H0:μstandard = μnone</p>
<p><strong>H₁₃ (Alternative Hypothesis):<br>
</strong> Mean eye strain score is lower for standard gaming glasses than for no protection.</p>
<p>The mean for the eye strain score for standard gaming glasses is less than the mean eye strain score for no protection.</p>
<p>H1:μstandard &lt; μnone</p>
</section>
</section>
<section id="methods-and-results" class="level1">
<h1><strong>Methods and Results</strong></h1>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method">Method</h3>
<p>This study uses a repeated-measure approach to examine the effects of gaming eyewear during extended gaming sessions. The devices that participants used are: adaptive blue-filter, standard gaming glasses and no protection, and sessions where 5 hour gaming sessions. Each device was used over two sessions where the eye strain of the corresponding participant was documented and reported for each session.</p>
<p>Participants were randomly assigned to device condition at the first session, and this assignment was held constant for the second session. Because each participant was measured twice under the same treatment condition, observations were not independent. Therefore, gamer_id was included as a blocking factor using an Error term in the repeated-measures ANOVA to account for within-subject correlation.</p>
<p>A post-hoc analysis had to be performed as the third hypothesis was unable to be supported nor unsupported. To do this a package called emmeans was used to do the post-hoc comparisons, using estimated marginal means with Bonferroni correction to control multiple comparisons.</p>
</section>
<section id="data-description" class="level3">
<h3 class="anchored" data-anchor-id="data-description">Data Description</h3>
<p>The dataset that I was provided with, consisted of repeated measures of eye strain collected from the participant after they had completed one 5 hour gaming session using a randomly selected device and again after another 5 hour gaming session. Each participant were randomly assigned one of three devices:</p>
<ol type="1">
<li><p>Adaptive blue filter</p></li>
<li><p>Standard gaming glasses</p></li>
<li><p>No protection</p></li>
</ol>
<p>The dataset was structured in tidy format with one row per observation.</p>
<p>Because each participant was measured twice under the same condition, observations were not independent. Therefore, analysis required a repeated-measure approach that accounts for within subject correlation.</p>
<p>Because each participant was measured twice under the same treatment condition, observations were not independent. Therefore, analysis required a repeated-measures framework that accounts for within-subject correlation.</p>
</section>
<section id="statistical-approach" class="level2">
<h2 class="anchored" data-anchor-id="statistical-approach"><strong>Statistical Approach</strong></h2>
<p>A two-factor mixed repeated-measures ANOVA was done. Device was considered a between-subject factor and session as a within-subject factor. The ANOVA model includes an Error term to account for repeated measurements within participants:&nbsp;</p>
<p>eye_strain_score ~ device * session + Error(gamer_id/session),</p>
<p>I chose this approach over a standard two-way ANOVA because a simple ANOVA would violate the independence assumption. Including&nbsp; gamer_id as a blocking (grouping) factor.</p>
<p>The Statistical Significance was evaluated at 0.05.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("emmeans")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Read dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>eye_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"eye_strain_data.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Inspect structure</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(eye_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X session gamer_id               device eye_strain_score
1 1    2016        1 adaptive_blue_filter             79.2
2 2    2016        2 adaptive_blue_filter             83.7
3 3    2016        3 adaptive_blue_filter             83.8
4 4    2016        4 adaptive_blue_filter             90.8
5 5    2016        5 adaptive_blue_filter             83.5
6 6    2016        1 adaptive_blue_filter             94.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(eye_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   600 obs. of  5 variables:
 $ X               : int  1 2 3 4 5 6 7 8 9 10 ...
 $ session         : int  2016 2016 2016 2016 2016 2016 2016 2016 2016 2016 ...
 $ gamer_id        : int  1 2 3 4 5 1 2 3 4 5 ...
 $ device          : chr  "adaptive_blue_filter" "adaptive_blue_filter" "adaptive_blue_filter" "adaptive_blue_filter" ...
 $ eye_strain_score: num  79.2 83.7 83.8 90.8 83.5 94.5 95 96.8 95.7 96.3 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert categorical variables to factors</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>eye_data<span class="sc">$</span>device <span class="ot">&lt;-</span> <span class="fu">factor</span>(eye_data<span class="sc">$</span>device)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>eye_data<span class="sc">$</span>session <span class="ot">&lt;-</span> <span class="fu">factor</span>(eye_data<span class="sc">$</span>session)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>eye_data<span class="sc">$</span>gamer_id <span class="ot">&lt;-</span> <span class="fu">factor</span>(eye_data<span class="sc">$</span>gamer_id)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Fit repeated-measures ANOVA</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  eye_strain_score <span class="sc">~</span> device <span class="sc">*</span> session <span class="sc">+</span> <span class="fu">Error</span>(gamer_id<span class="sc">/</span>session),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> eye_data</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="do">## Display ANOVA summary</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: gamer_id
          Df Sum Sq Mean Sq F value Pr(&gt;F)
device     1   76.4   76.42   0.273  0.637
Residuals  3  838.4  279.48               

Error: gamer_id:session
          Df Sum Sq Mean Sq F value Pr(&gt;F)   
device     1    913     913   7.712 0.0692 . 
session    1   4774    4774  40.336 0.0079 **
Residuals  3    355     118                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
device           2   1708   853.8  26.364 1.09e-11 ***
device:session   2     63    31.3   0.965    0.382    
Residuals      585  18946    32.4                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create summary table</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  eye_strain_score <span class="sc">~</span> device <span class="sc">+</span> session,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> eye_data,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(x), <span class="at">sd =</span> <span class="fu">sd</span>(x))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Expand results</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">do.call</span>(data.frame, summary_table)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Rename columns</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(summary_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Device"</span>, <span class="st">"Session"</span>, <span class="st">"Mean"</span>, <span class="st">"SD"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Print</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>summary_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Device Session     Mean       SD
1    adaptive_blue_filter    2016 82.29400 8.411726
2           no_protection    2016 85.00100 7.244650
3 standard_gaming_glasses    2016 85.87475 5.789440
4    adaptive_blue_filter    2017 87.86600 4.489724
5           no_protection    2017 92.05100 4.030853
6 standard_gaming_glasses    2017 91.69400 3.397766</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">##post-hoc </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(eye_strain_score <span class="sc">~</span> device <span class="sc">*</span> session, <span class="at">data =</span> eye_data)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Get estimated marginal means by device within each session (post-hoc)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>emm_device_session <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model, pairwise <span class="sc">~</span> device <span class="sc">|</span> session, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Extract only the emmeans (ignores contrasts for now)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>emmeans_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(emm_device_session<span class="sc">$</span>emmeans)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Round numeric columns for reporting</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>emmeans_table<span class="sc">$</span>emmean <span class="ot">&lt;-</span> <span class="fu">round</span>(emmeans_table<span class="sc">$</span>emmean, <span class="dv">1</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>emmeans_table<span class="sc">$</span>SE <span class="ot">&lt;-</span> <span class="fu">round</span>(emmeans_table<span class="sc">$</span>SE, <span class="dv">2</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>emmeans_table<span class="sc">$</span>lower.CL <span class="ot">&lt;-</span> <span class="fu">round</span>(emmeans_table<span class="sc">$</span>lower.CL, <span class="dv">2</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>emmeans_table<span class="sc">$</span>upper.CL <span class="ot">&lt;-</span> <span class="fu">round</span>(emmeans_table<span class="sc">$</span>upper.CL, <span class="dv">2</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns to match your example</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(emmeans_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Device"</span>, <span class="st">"Session"</span>, <span class="st">"Mean"</span>, <span class="st">"SE"</span>, <span class="st">"df"</span>, <span class="st">"LowerCI"</span>, <span class="st">"UpperCI"</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the columns you want for your table (Device, Session, Mean, SE)</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>emmeans_table <span class="ot">&lt;-</span> emmeans_table[, <span class="fu">c</span>(<span class="st">"Device"</span>, <span class="st">"Session"</span>, <span class="st">"Mean"</span>, <span class="st">"SE"</span>)]</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Print</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(emmeans_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Device Session Mean   SE
1    adaptive_blue_filter    2016 82.3 0.58
2           no_protection    2016 85.0 0.58
3 standard_gaming_glasses    2016 85.9 0.59
4    adaptive_blue_filter    2017 87.9 0.58
5           no_protection    2017 92.1 0.58
6 standard_gaming_glasses    2017 91.7 0.58</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Device</th>
<th>Session</th>
<th>Mean</th>
<th>SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>adaptive_blue_filter</td>
<td>2016</td>
<td>82.3</td>
<td>0.58</td>
</tr>
<tr class="even">
<td>no_protection</td>
<td>2016</td>
<td>85</td>
<td>0.58</td>
</tr>
<tr class="odd">
<td>standard_gaming_glasses</td>
<td>2016</td>
<td>85.9</td>
<td>0.59</td>
</tr>
<tr class="even">
<td>adaptive_blue_filter</td>
<td>2017</td>
<td>87.9</td>
<td>0.58</td>
</tr>
<tr class="odd">
<td>no_protection</td>
<td>2017</td>
<td>92.1</td>
<td>0.58</td>
</tr>
<tr class="even">
<td>standard_gaming_glasses</td>
<td>2017</td>
<td>91.7</td>
<td>0.58</td>
</tr>
</tbody>
</table>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results"><strong>Results</strong></h2>
<p>A two-factor mixed repeated-measures ANOVA was conducted to examine the effects of eye protection device and session on eye strain. The analysis revealed a significant main effect of device, F(2, 585) = 26.36, p &lt; .001, indicating that mean eye strain differed across the three types of eye protection. There was also a significant main effect of session, F(1, 3) = 40.34, p = .0079, suggesting that eye strain increased from Session 1 to Session 2. The device × session interaction was not significant, F(2, 585) = 0.97, p = .382, indicating that the increase in eye strain over time was similar across all devices.</p>
<p>Post-hoc comparisons using estimated marginal means (emmeans) with Bonferroni correction indicated that, in both sessions, the adaptive blue filter resulted in significantly lower eye strain than both no protection (2016: M = 82.3, SE = 0.58 vs 85.0, SE = 0.58; 2017: M = 87.9, SE = 0.58 vs 92.1, SE = 0.58) and standard gaming glasses (2016: M = 82.3, SE = 0.58 vs 85.9, SE = 0.59; 2017: M = 87.9, SE = 0.58 vs 91.7, SE = 0.58). There was no significant difference between standard gaming glasses and no protection in either session. Comparisons across sessions for each device indicated that eye strain increased significantly from 2016 to 2017 for all devices: adaptive blue filter (M difference = 5.57, SE = 0.58), standard gaming glasses (M difference = 5.82, SE = 0.59), and no protection (M difference = 7.05, SE = 0.58).</p>
<p>Overall, the adaptive blue filter consistently produces results showing lower eye strain, however, all types of eye protection have similar increases in eye strain over time.</p>
</section>
<section id="interpretation-relative-to-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-relative-to-hypotheses"><strong>Interpretation Relative to Hypotheses</strong></h2>
<ul>
<li><p><strong>H₁₁:</strong> Supported. Device type significantly influenced eye strain.<br>
<br>
</p></li>
<li><p><strong>H₁₂:</strong> Not supported. No evidence of a persistence or carry-over advantage for the adaptive device.<br>
<br>
</p></li>
<li><p><strong>H₁₃:</strong> Not supported. Standard gaming glasses did not reduce eye strain by a significant amount when compared to no protection.</p></li>
</ul>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In conclusion, despite the adaptive blue light filtering device significantly lowers participants eye strain during extended gaming sessions compared to both standard gaming glasses and no protection. The eye strain increased over the duration of session 2 for all participants, and the adaptive blue light filtering device did not maintain a stronger protection over time. Overall, the adaptive blue light filtering device provides an immediate benefit to the user but there is no evidence to suggest that the effectiveness improves or persists over multiple sessions.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>I used AI to help me understand the analysis and to help me clarify my understanding.</p>
<p>Pardhan, S. et al.&nbsp;(2022) Risks of Digital Screen Time and Recommendations for Mitigating Adverse Outcomes in Children and Adolescents. The Journal of school health. [Online] 92 (8), 765–773.</p>
<p>(Accessed: 24/02/2026)</p>
<p>Rosenfield, M., 2011. Computer vision syndrome: a review of ocular causes and potential treatments. Ophthalmic and Physiological Optics, 31(5), pp.502-515.</p>
<p>(Accessed : 15/02/2026)</p>
<p>Sheppard, A.L. and Wolffsohn, J.S., 2018. Digital eye strain: prevalence, measurement and amelioration. BMJ open ophthalmology, 3(1).</p>
<p>(Accessed: 13/02/2026)</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>